wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.0
    framework: huggingface
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717556590
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 23
      4: 3.9.19
      5: 0.17.0
      8:
      - 1
      - 5
      13: linux-x86_64
